#!/usr/bin/env ansible-playbook
---
- name: Ubuntu
  hosts: "{{ custom_hosts | default('all') }}"
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: Upgrade system
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      async: 3600
      poll: 5
      tags:
        - system
        - upgrade

    - name: Install basic security packages
      ansible.builtin.apt:
        state: present
        update_cache: yes
        name:
          - ufw
          - gufw
          - unattended-upgrades
          - iptables-persistent
          - logcheck
      tags:
        - system
        - sec

    - name: Install tools
      ansible.builtin.apt:
        state: present
        update_cache: yes
        name:
          - rsync
          - vim
          - vim-gui-common
          - vim-runtime
          - tmux
          - htop
          - curl
          - expect
          - tree
          - build-essential 
          - procps
          - file
          - acl
          - git
          - jq
          - p7zip-full
          - zip
          - unzip
          - unrar-free
          - arj
          - ark
          - unp
          - python3
          - python3-pip
          - python3-venv
          - python3-apt
          - python3-setuptools
          - python3-yaml
          - python3-defusedxml
          - bash-completion
          - apt-transport-https
          - apt-file
          - command-not-found
          - gnupg2
          - gnupg-agent
          - keepass2
          - pwgen
          - resolvconf
          - remmina
          - transmission
          - wireshark
          - nmap
          - tcpdump
          - dnsutils
          - dsniff
          - telnet
          - ipcalc
          - iptraf
          - nethogs
          - shellcheck
          - flameshot
          - renameutils # qmv, qcp, et al.
          - units
          - software-properties-common
          - strace
          - cmake
          - lshw
          - ccze
          - djvulibre-bin 
          - ghostscript
          - gnuplot
          - pdftk
          - cmus
      tags:
        - system
        - tools   

    - name: Role andreswebs.docker
      include_role:
        name: andreswebs.docker
      tags:
        - docker

    - name: Role andreswebs.nodejs
      include_role:
        name: andreswebs.nodejs
      tags:
        - nodejs
