#!/usr/bin/env ansible-playbook
---
- name: Ubuntu
  hosts: "{{ custom_hosts | default('all') }}"
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true

  tasks:
    - name: Base
      ansible.builtin.include_tasks: tasks/base.yml
      tags:
        - base

    - name: Desktop
      ansible.builtin.include_tasks: tasks/desktop.yml
      tags:
        - desktop

    - name: Flatpak
      ansible.builtin.include_tasks: tasks/flatpak.yml
      when: flatpak is defined
      tags:
        - flatpak

    - name: Android
      ansible.builtin.include_tasks: tasks/android.yml
      when: android is defined
      tags:
        - android

    - name: Notes
      ansible.builtin.include_tasks: tasks/notes.yml
      when: android is defined
      tags:
        - android

    - name: Role andreswebs.docker
      ansible.builtin.include_role:
        name: andreswebs.docker
      tags:
        - docker
