---
- name: base | Upgrade system
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    autoclean: true
  async: 3600
  poll: 5
  when: upgrade_system | default(false) | bool
  tags:
    - system
    - upgrade

- name: base | Install apparmor
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - apparmor
      - apparmor-profiles
      - apparmor-profiles-extra
      - apparmor-utils
  tags:
    - system
    - apparmor

- name: base | Install python libs
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-apt
      - python3-setuptools
      - python3-yaml
      - python3-defusedxml
      - python3-cairo
      - python3-dbus
      - python3-gi
      - python3-pbr
  tags:
    - system
    - tools
    - python

- name: base | Install tools
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - rsync
      - vim
      - vim-gui-common
      - vim-runtime
      - gettext-base
      - tmux
      - htop
      - curl
      - expect
      - tree
      - build-essential
      - procps
      - file
      - acl
      - git
      - jq
      - p7zip-full
      - zip
      - unzip
      - unrar-free
      - arj
      - ark
      - unp
      - bash-completion
      - apt-transport-https
      - apt-file
      - command-not-found
      - gnupg
      - pwgen
      - nmap
      - tcpdump
      - dnsutils
      - dsniff
      - telnet
      - ipcalc
      - iptraf
      - nethogs
      - renameutils # qmv, qcp, et al.
      - units
      - software-properties-common
      - strace
      - cmake
      - lshw
      - ccze
      - fwupdmgr
  tags:
    - system
    - tools
