---
- name: desktop | Install desktop tools
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - keepass2
      - remmina
      - transmission
      - wireshark
      - djvulibre-bin
      - ghostscript
      - gnuplot
      - pdftk
      - cmus
      - gufw
  tags:
    - desktop
#
#
# - name: desktop | Install telegram
#   community.general.snap:
#     state: present
#     name:
#       - telegram-desktop
#   tags:
#     - telegram

- name: desktop | Install telegram
  community.general.flatpak:
    state: present
    remote: flathub
    name:
      - org.telegram.desktop
  tags:
    - desktop
