---
- name: desktop | Install desktop tools
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - keepass2
      - remmina
      - transmission
      - wireshark
      - djvulibre-bin
      - ghostscript
      - gnuplot
      - pdftk
      - cmus
      - gufw
  tags:
    - desktop
