---
- name: flatpak | Install Flatpak
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - flatpak
  tags:
    - flatpak

- name: flatpak | Install Flatpak GUI plugin
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - xdg-desktop-portal
      - xdg-desktop-portal-xapp
  tags:
    - flatpak

- name: flatpak | Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: system
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak

- name: flatpak | Install telegram
  community.general.flatpak:
    state: present
    remote: flathub
    name:
      - org.telegram.desktop
  tags:
    - telegram
