---
- name: notes | Install notes
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/pimterry/notes/latest-release/notes
    dest: /usr/local/bin/notes
    owner: root
    group: root
    mode: "0755"
  tags:
    - notes

- name: notes | Install notes bash completion
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/pimterry/notes/latest-release/notes.bash_completion
    dest: /etc/bash_completion.d/notes
    owner: root
    group: root
    mode: "0644"
  tags:
    - notes
