---
- name: Install pass
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - pass
  tags:
    - pass

# https://github.com/roddhjav/pass-import
- name: Add pass-extension-import GPG key
  ansible.builtin.apt_key:
    state: present
    url: https://pkg.pujol.io/debian/gpgkey
    keyring: /etc/apt/trusted.gpg.d/pass-import.gpg
  tags:
    - pass

- name: Add pass-extension-import APT repository
  ansible.builtin.apt_repository:
    state: present
    repo: deb [arch=amd64] https://pkg.pujol.io/debian/repo all main
    filename: pass-import
  tags:
    - pass

- name: Install pass extensions
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - pass-extension-import   
  tags:
    - pass

- name: Install pykeepass
  ansible.builtin.pip:
    name: pykeepass
  tags:
    - pass
